### ISSUE TITLE
LXQt metapackage: Calibre hijacks too many mime types - please downgrade from recommended to suggested

### ISSUE THREAD

**Issue by user20190106** [lxqt/lxqt#1654]
Note: This may be a Debian bug (or "feature"), but may be the same in other distros as well.

##### Expected Behavior
After installing the `lxqt` metapackage, a html document should continue to open in a browser, an *.odt should continue to open in a word processing software, a *.txt file should continue to open in a text processor without the need to select the application from the context menu, **NOT** in an eBook application.

##### Current Behavior
In the above cases, `Calibre` opened as default unless one of possible solutions below is applied, as it has effectively hijacked a very long list of mimetypes in its desktop file.

For instance, when trying to open `LibreOffice` help, instead of a web browser, I got `Calibre`, which made me really confused - and  was blaming `LibreOffice` - do I need to somehow compile the help to an eBook before I can use it???? And [wrongly] noted down for myself "Offline help does not work in LO 6.1.4" after having  used quite some time for searching solutions to problems with LO's offline help. 

##### Possible Solutions (that a user can apply)
1. Instead of installing the metapackage, hand-pick packages. - Not a solution for a lazy or a novice or someone who wants to make trial installation
2. Create a `~/.config/mimeapps.list` and redefine your normal applications for all mime types listed in `Calibre`'s desktop file - A lot of work, a user should not need to do this.

However,  I *did* this (after using considerable time for searching information and then to do the file was lot of work) -- but later on I noticed that it didn't always work. For instance, `QtWebEngine` does not seem to know about the `~/.config/mimeapps.list` and I got again `Calibre` in certain cases.

3. Uninstall `Calibre`
Was the perfect solution for me, should have done it immediately. 

##### Suggested solution
Downgrade `Calibre` from recommended to suggested, i.e. do not include in the automatic installation.

##### Steps to Reproduce
1.  Do a clean Debian Buster install as recommended (first install Debian Stretch, then upgrade).
2. Install the `lxqt` metapackage.
3. After installation, double-click an *.odt file. `Calibre` opens instead of LO Writer. Or try to open LibreOffice Help. (And as far as I can remember, even *.txt files got opened in `Calibre`

##### Context

I think the context is clear from above. The issue made me pissed of, made me wrongly accuse  other software and made sure that if I ever am going to need an eBook software, it is definitely not going to be `Calibre`!  On the bright side, I learned about mimetype handling.

##### System Information

* Distribution & Version: Debian Buster, installed on 2019-01-12
* Kernel: 4.19
* Qt Version: 
* liblxqt Version: 
* Package version:

**Comment by tsujan** [comment]
Most probably, you haven't installed libfile-mimeinfo-perl, which should be among recommends.

**Comment by user20190106** [comment]
I *had* (and still have) `libfile-mimeinfo-perl` installed. 

To repeat:
1. Did a clean install of Debian Stretch
2. Upgraded Debian Stretch to Debian Buster. `libfile-mimeinfo-perl` shows in the log of installed packages.
3. Used the system a bit with LXDE (as LXQt was not on the list one could choose from when installing Stretch).  *.odt-files opened correctly in LO. (Didn't yet test LO's help, though - if I had seen the new LO html help before installing `lxqt`, I probably could have saved some time and  figured out the culprit earlier).   
4. Installed `lxqt`
5. Started wondering why this eBook application I had never heard of now appears everywhere when I just try to do the same as before - open a file by double-clicking.
6. Did extensive web search and self-study on how mimetypes are handled.
7. Examined desktop file of `Calibre` which listed the following mimetypes:
```
MimeType=text/plain;application/x-mobipocket-subscription;application/vnd.openxmlformats-officedocument.wordprocessingml.document;text/html;application/x-cbc;application/ereader;application/oebps-package+xml;image/vnd.djvu;application/x-sony-bbeb;application/vnd.ms-word.document.macroenabled.12;text/rtf;text/x-markdown;application/pdf;application/x-cbz;application/x-cbr;application/x-mobi8-ebook;text/fb2+xml;application/vnd.oasis.opendocument.text;application/epub+zip;application/x-mobipocket-ebook;application/xhtml+xml;
```
8. Examined `/usr/share/applications/mimeinfo.cache`. `Calibre`appeared as the first choice for each mime type I experienced problems with, for instance:
```
application/vnd.oasis.opendocument.text=calibre-gui.desktop;libreoffice-writer.desktop;calibre-ebook-viewer.desktop;
```
9. Created a long `~/.config/mimeapps.list` to override the obnoxious behaviour of `Calibre`
10. After a few days noticed that this didn't help in certain circumstances and decided uninstall `Calibre` and never install it again.

=== 
The moral of this story is: if  `Calibre` continues to be included in the applications installed as default when installing the `lxqt` metapackage once Buster is released, there will be a lot of confused users and bugs reported to other, completely innocent applications, such as LO. Which is the exact reason why I  reported this issue - I didn't need to, as  I had solved it for myself.

Or at least the desktop file of `Calibre` should be stripped to bare minimum, listing only he mimetypes of eBooks; users who *want* to use `Calibre` to open all possible files from plain text to html to word processing should then do their own overrides in `mimeapps.list`.  As far as I understood from my mimetype studies, there is currently no possibility to define priority order on system level: last installed seems to get  first on the list. [Which is quite stupid - last installed should be last on the list].

**Comment by tsujan** [comment]
Here, on Manjaro, I'd installed Calibre a year ago or so and didn't have any problem with file openeing. Later, I didn't like Calibre and uninstalled it.

Minutes ago, I installed that monstrosity again. I see none of your problems here, while, for example, I have no entry about html or `application/vnd.oasis.opendocument.text` in `~/.config/mimeapps.list`.

The problem is definitely not in LXQt. Since you have `libfile-mimeinfo-perl`, I don't have a clue why you see what you see.

**Comment by tsujan** [comment]
And if you're sure that Debian's Calibre does what it does because of its desktop file, you should report that to its Debian maintainer -- your voice won't be heard by Debian here.

FYI, these are Calibre's types in Arch:

```
MimeType=application/x-cbr;application/x-cbc;application/ereader;application/oebps-package+xml;image/vnd.djvu;application/x-sony-bbeb;application/vnd.ms-word.document.macroenabled.12;application/x-mobipocket-subscription;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/x-mobipocket-ebook;application/vnd.ctc-posml;application/x-mobi8-ebook;application/epub+zip;application/x-cbz;
```

**Comment by user20190106** [comment]
Well,  correlation of samples  analyzed  was 100%, but as the high correlation between number of  people drowning and consumption of ice cream demonstrates, correlation does not infer causality. So I cannot say for sure, because I'm not competent enough to judge.

However, my unproven theory is that the underlying cause of the problem is that the way how `mimeinfo.cache` is updated when new packages are installed is fundamentally flawed. Instead of FIFO, it seems to apply LIFO. Which may lead to erratic results depending on the order in which packages get installed, and with high potential of creating confused and dissatisfied users.

The sad end result is that the badwill generated won't be distributed  "correctly": the logical conclusion of a user who experiences problems after installing LXQt will be that LXQt is to blame. SABENA from the user's standpoint.

Anyway,  the issue is not relevant for me any longer, as I know what to do.

**Comment by tsujan** [comment]
> the logical conclusion of a user... will be that LXQt is to blame.

So "logical"!

**Comment by agaida** [comment]
If calibre captures to much mime-types - upps - that should be fixed in calibre. Otherwise, downgrading calibre to Suggests might be the right thing to do. Given that the mime handling in Linux/Debian/whatever is crap this would not solve any problem. Maybe the TC in Debian might be the right place to ask :sunglasses:

**Comment by agaida** [comment]
@user20190106 - you are wrong, mime-type handling in linux is just perfect. \<sarcasm\>

**Comment by tsujan** [comment]
@agaida Joking aside, yes and no. Yes, because having a mechanism to guess mimetypes based on both extension and magic, flexible app association, established standards, nice tools like gio/GIO, etc. are the best I can think of -- IMHO, we, Linux users, take these for granted. But no, because guessing a mimetype only based on a few "#" signs, for example, is a ridiculous use of the available resources.

The more flexible something is, the more carefully it should be used. There are always careless codes and we can't be responsible for the whole world. I'm sure we agree on this.

**Comment by user20190106** [comment]
I agree that downgrading Calibre from recommended to suggested does not solve the real problem – it only helps in mitigating consequences in some cases.

When I ran `ls -ltc` in `/usr/share/applications`, the order of applications in mimeinfo.cache seemed mostly be the reverse of installation time – but not always.

Also, Calibre was not the only application which was ”wrongly placed”. But the problem is not that severe for file types the user opens by double-clicking in a file manager: the user can right-click and pick another application, and even change the file association right away. A bit annoying and should not be necessary, but problem solved.

But the case where an eBook application gets first for `text/html` instead of a browser is quite critical, as offline help nowadays most often consists of html files. The user presses F1 or selects Help from the menu – and an eBook application never seen before opens. Utterly confusing. No right-click menu. Application broken, at least for a user who had previously used  traditional offline help.

The user might get it corrected if s/he doubled-clicked an html file in a file manager with the same result – but how often do people have offline html files that they would use through a file manager? On the other hand, any text editor or word processing software can open html files – but wisely enough, none of the ones I have installed listed text/html in their desktop files.

I wonder why nothing has been done to correct the root cause, i.e. that order of applications per mimetype in `mimeinfo.cache`  is doubly wrong – it seems to be LIFO combined with a degree of randomness to make life interesting.  So much time lost, so many questions in user forums, so much redundant work throughout the entire Linux community.

It cannot be rocket science to sort a couple of hundred desktop files so that results are predictable and stable. For instance, start from the current list, purge it from applications that are not there any more, sort by `ctime` and then loop through from oldest to newest and add those missing from previous version of the list at the end of each mimetype. This would already eliminate quite many problems users are experiencing, although not alone sufficient.

(P.S. I just discovered the directory plugin. Awesome! Only that when I wanted to open a directory in a file manager, Baobab opened instead… ...it had hijacked the `inode/directory` entry in `mimeinfo.cache`. )

**Comment by agaida** [comment]
If you want mime-types with your preferred settings - override them in your profile. Should be no rocket science. Btw - the handling of types automagically is also wrong in Windows - so it is not a LXQt or Linux problem. Some times the user has to do the dirty work, no spells, no silver bullets available.

**Comment by user20190106** [comment]
> Some times the user has to do the dirty work, no spells, no silver bullets  available.

That’s what I tried to refer to with the sentence ”although not alone sufficient”. If Firefox is the first browser installed and I install Chromium and want to make it default, *that* I have to do myself. This I do understand, and is easy to do, because the browser will ask for it the first time you open it (at least on Windows).

But if I have used Firefox for  text/html *for years* without needing to *any* such ”dirty work” myself, why should I suddenly need to get my hands dirty after installing some unrelated non-browser software? *That’s* completely redundant work that could be avoided if `mimeinfo.cache` were updated according to FIFO.

When something that worked before suddenly stops working is very confusing for users.

Anyway, I apologize, I know this is not the right forum, and as I've said before, I only reported this in the hope that it would help other people to avoid redundant work.

**Comment by tsujan** [comment]
> they missed some thing like mime-type priorities

@agaida It wouldn't solve any problem because an app with a "higher priority mime type" could be installed.

We have `[Default Applications]` inside `(lxqt-)mimeapps.list`, which is like Debian's "alternatives" (BTW, I miss "alternatives" in Arch's structure).

Last, my personal story made short: when, 15 years ago, I came to Linux from the crappy Windows XP, one of several things that caught my admiring attention from start was what we call mimetypes handling -- those days I didn't know its name. Frankly, whenever I've had problems with mimetypes, it has been because of a coding mistake or an incomplete installation, not because of mimetype handling itself.
