### ISSUE TITLE
Keyboard layout indicator in tray shows "??" instead of "RU" for Russian

### ISSUE THREAD

**Issue by ssrublev** [lxqt/lxqt#2165]
Keyboard layout indicator in tray shows "??" instead of "RU" for Russian when Russian is added to keyboard layouts. Impossible to use flags because flag directory is also refers to "??" in path.

Affected both Ubuntu and Fedora. Ubuntu bug filed at https://bugs.launchpad.net/ubuntu/+source/lubuntu-meta/+bug/1955179

**Comment by tsujan** [comment]
I'm afraid this is a downstream issue. As far as upstream is concerned, you could put any flag there. The code is so flexible that you could change a flag to an image too.

> Ubuntu bug filed at....

You did the right thing. We have no control over distros here.

I close this but if you think there's a problem with a certain flag *in LXQt*, please tell us by describing a way of reproducing it; then the issue will be reopened.

**Comment by stefonarch** [comment]
In Lubuntu 21.10 VM I cannot see any issue with RU, so I think there are other settings involved. Type of keyboard?

**Comment by tsujan** [comment]
@stefonarch 
The title @ssrublev chose was misleading. He meant Russian *flag* (in Ubuntu/Fedora), not Russian keyboard layout.

I'm changing the title....

**Comment by stefonarch** [comment]
I understood both, flag and text.

**Comment by tsujan** [comment]
> I understood both, flag and text.

Yes, they have no problem on our side; hence closing the issue.

**Comment by stefonarch** [comment]
I can reproduce a similar thing with "MacIntosh" keyboard for example, adding more language one of them will reproduce ?? and not neccessary russian, with and without flags (move mouse cursor out of the video)



https://user-images.githubusercontent.com/10681413/146686395-04561dbd-19aa-4a96-b42f-2cc49aa9ad4a.mp4

**Comment by ssrublev** [comment]
> In Lubuntu 21.10 VM I cannot see any issue with RU, so I think there are other settings involved. Type of keyboard?

Fedora finds it as "Generic 105-key PC".

In LXQt, when I go to settings, I go to "Keyboard layout". I can "Add" new layout. When I add, I can select a layout. I go to "Russian". There is the column "Variant". 

Variants of Russian are presented. But I need the variant "None" — the default common layout. All other variants are irrelevant. If I select "Russian (legacy)", the bug is gone. I can switch languages and see in systray indicator "EN" and "RU".

But "Russian (legacy)" is a bad choice. It has wrong keys. I need only "None" variant. The keyboard types correctly then.

But when I do it, systray indicator switches between "EN" and "??". In both distros. That's the problem.

With "??", it is also impossible to use "Flags path pattern" in "Keyboard state settings". Because it goes to use "??.svg" file.

**Comment by stefonarch** [comment]
There has to be something else hidden - I cannot reproduce it neither  in Lubuntu 21.10 nor on my main machine with git, "none" and every other variant of russian I tested are ok.

**Comment by stefonarch** [comment]
>Because it goes to use "??.svg" file.
 
Maybe as workaround you could copy `ru.svg` to `??.svg`?

**Comment by ssrublev** [comment]
> EDIT: what happens if you add a third language?

When I add "Ukrainian" (variant "None"), it switches between "US", "??", "UA"

When I also add "Belarusian (legacy)", it shows "US", "??", "UA", "BY"

the same for "Belarusian" → "None"

**Comment by ssrublev** [comment]
> > Because it goes to use "??.svg" file.
> 
> Maybe as workaround you could copy `ru.svg` to `??.svg`?

Great, it worked! 

The path "/usr/share/iso-flag-png/%1.png" can use "??.png" and show the flag, thanks!

**Comment by ssrublev** [comment]
Checked in both Fedora and Ubuntu. Workaround works in both.

**Comment by tsujan** [comment]
Yes, it's a good workaround but please note that there's a problem in the system you use that doesn't exist in @stefonarch's and my systems. We still don't know what it is.

**Comment by ssrublev** [comment]
Well, I use an alternately modified file "/usr/share/X11/xkb/symbols/ru" in both distros

There are redefined keys for use with Wiki markup, described here https://en.wikipedia.org/wiki/User:Ssr/styledemo#My_custom_Linux_xkb_Cyrillic_keyboard_layout

This may affect. 

The "??" issue only concerns LXQt, not MATE, KDE, Gnome or XFCE that I have.

**Comment by stefonarch** [comment]
Quite sure this is the cause, you could make a test with the default file but it's 99%

**Comment by tsujan** [comment]
Panel's code only reads `/usr/share/X11/xkb/rules/evdev.xml`. Even if we don't consider `base.extras.xml` in the same directory (why?), I think hard-coding `/usr/share` is suspicious. IMHO, the code isn't optimal.

**Comment by tsujan** [comment]
Another report, at https://github.com/lxqt/lxqt-panel/issues, may be needed but not just for this special case. There should be more issues, that most users don't encounter. I don't know how to describe them; "suboptimal code"?

**Comment by ssrublev** [comment]
It is also strange grouping for layouts I see in "Russian" layout section. Under "Russian", it contains languages such as Tatar, Bashkirian, Komi, Udmurt and even Serbian.

Tatar is completely different from Russian. It's Turkic, while Russian is Slavonic. Komi is Finno-Ugric. They are not "Russian".

Most probably, this indicates that they are Cyrillic, per alphabet. 

"Russian" here probably means "related to Russia as country", not "Russian as language".

**Comment by luis-pereira** [comment]
> Panel's code only reads `/usr/share/X11/xkb/rules/evdev.xml`. Even if we don't consider `base.extras.xml` in the same directory (why?), I think hard-coding `/usr/share` is suspicious. IMHO, the code isn't optimal.

Sub-optimal. Will take care (at least) of the hardcoded paths.

**Comment by tsujan** [comment]
> Will take care (at least) of the hardcoded paths.

Thanks!

**Comment by luis-pereira** [comment]
Fixed the harcoded paths. 

> On Linux systems, the evdev rules are most commonly used, on other systems the base rules are used.
States the XKB configuation manual. I used `XkbRF_VarDefsRec()` to get the rule in use, tough.
It seems that `lxqt-panel/plugin-kbindicator` and the config tool `lxqt-config-input` need some love.
Will continue on it after Christmas. Will publish after fixing some things found while browsing the code
Merry Christmas!

**Comment by stefonarch** [comment]
Merry Christmas!

**Comment by tsujan** [comment]
Merry Christmas to you all!

**Comment by ssrublev** [comment]
And Happy Chinese New Year! =))) (February 1)

Just here to say that I now have LXQt 1.0 which is supplied by Fedora Rawhide. This issue still persists there. lxqt-panel.x86_64 version is 1.0.0-2.fc36
