### ISSUE TITLE
lxqt-panel dumps core 

### ISSUE THREAD

**Issue by renegat** [lxqt/lxqt#958]
lxqt-panel 0.10.0-5
4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

On every suspend/wakeup and irregular going along with weird graphical issues (ghost icons):

Sometimes according to libQt5XcbQpa.so.5.5.1 or libQt5Gui.so.5.5.1:

```
kernel: traps: lxqt-panel[841] general protection ip:7f40bb420241 sp:7ffce4c9b860 error:0 in libQt5XcbQpa.so.5.5.1[7f40bb3d1000+e0000]
systemd-coredump[5302]: Process 841 (lxqt-panel) of user 1000 dumped core.

Stack trace of thread 841:
#0  0x00007f40bb420241 _ZNK10QXcbWindow11mapToNativeERK5QRectPK10QXcbScreen (libQt5XcbQpa.so.5)
#1  0x00007f40bb426c73 _ZN10QXcbWindow11setGeometryERK5QRect (libQt5XcbQpa.so.5)
#2  0x00007f40c4ff150c _ZN14QWidgetPrivate15setGeometry_sysEiiiib (libQt5Widgets.so.5)
#3  0x00007f40c4ff1f60 _ZN7QWidget11setGeometryERK5QRect (libQt5Widgets.so.5)
#4  0x00007f40c4fd97b4 _ZN11QWidgetItem11setGeometryERK5QRect (libQt5Widgets.so.5)
#5  0x0000000000435654 _ZN15LXQtPanelLayout15setItemGeometryEP11QLayoutItemRK5QRectb (lxqt-panel)
#6  0x0000000000437212 _ZN15LXQtPanelLayout16setGeometryHorizERK5QRect (lxqt-panel)
#7  0x0000000000437f15 _ZN15LXQtPanelLayout11setGeometryERK5QRect (lxqt-panel)
#8  0x00007f40c4fd5aff _ZN14QLayoutPrivate8doResizeERK5QSize (libQt5Widgets.so.5)
#9  0x00007f40c4fd7748 _ZN7QLayout8activateEv (libQt5Widgets.so.5)
#10 0x00007f40c4ff923d _ZN7QWidget10setVisibleEb (libQt5Widgets.so.5)
#11 0x000000000046ad54 n/a (lxqt-panel)
#12 0x000000000046c89c n/a (lxqt-panel)
#13 0x00007f40c46f231a _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
#14 0x00007f40b1f7dc08 n/a (KF5WindowSystemX11Plugin.so)
#15 0x00007f40c46c070f _ZN24QAbstractEventDispatcher17filterNativeEventERK10QByteArrayPvPl (libQt5Core.so.5)
#16 0x00007f40bb40ddc4 _ZN14QXcbConnection14handleXcbEventEP19xcb_generic_event_t (libQt5XcbQpa.so.5)
#17 0x00007f40bb40eb73 _ZN14QXcbConnection16processXcbEventsEv (libQt5XcbQpa.so.5)
#18 0x00007f40c46f31e1 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
#19 0x00007f40c4fb69ac _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#20 0x00007f40c4fbbe86 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#21 0x00007f40c46c3bab _ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent (libQt5Core.so.5)
#22 0x00007f40c46c5fa6 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
#23 0x00007f40c471a143 n/a (libQt5Core.so.5)
#24 0x00007f40c69c0dc7 g_main_context_dispatch (libglib-2.0.so.0)
#25 0x00007f40c69c1020 n/a (libglib-2.0.so.0)
#26 0x00007f40c69c10cc g_main_context_iteration (libglib-2.0.so.0)
#27 0x00007f40c471a54f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#28 0x00007f40c46c157a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#29 0x00007f40c46c953c _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#30 0x00000000004273d4 n/a (lxqt-panel)
#31 0x00007f40c3a39610 __libc_start_main (libc.so.6)
#32 0x0000000000427a69 _start (lxqt-panel)

Stack trace of thread 958:
#0  0x00007f40c3af918d poll (libc.so.6)
#1  0x00007f40b09b2251 n/a (libpulse.so.0)
#2  0x00007f40b09a3801 pa_mainloop_poll (libpulse.so.0)
#3  0x00007f40b09a3e9e pa_mainloop_iterate (libpulse.so.0)
#4  0x00007f40b09a3f50 pa_mainloop_run (libpulse.so.0)
#5  0x00007f40b09b2199 n/a (libpulse.so.0)
#6  0x00007f40b044ac98 n/a (libpulsecommon-8.0.so)
#7  0x00007f40c2fc24a4 start_thread (libpthread.so.0)
#8  0x00007f40c3b0213d __clone (libc.so.6)

Stack trace of thread 870:
#0  0x00007f40c3af516d __read (libc.so.6)
#1  0x00007f40c6c8a02e n/a (libmenu-cache.so.3)
#2  0x00007f40c69e7715 n/a (libglib-2.0.so.0)
#3  0x00007f40c2fc24a4 start_thread (libpthread.so.0)
#4  0x00007f40c3b0213d __clone (libc.so.6)

Stack trace of thread 854:
#0  0x00007f40c3af918d poll (libc.so.6)
#1  0x00007f40c2b8cae2 n/a (libxcb.so.1)
#2  0x00007f40c2b8e757 xcb_wait_for_event (libxcb.so.1)
#3  0x00007f40bb40a379 n/a (libQt5XcbQpa.so.5)
#4  0x00007f40c44e2b8e n/a (libQt5Core.so.5)
#5  0x00007f40c2fc24a4 start_thread (libpthread.so.0)
#6  0x00007f40c3b0213d __clone (libc.so.6)

Stack trace of thread 885:
#0  0x00007f40c3af918d poll (libc.so.6)
#1  0x00007f40c69c0fbc n/a (libglib-2.0.so.0)
#2  0x00007f40c69c10cc g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f40c69c1109 n/a (libglib-2.0.so.0)
#4  0x00007f40c69e7715 n/a (libglib-2.0.so.0)
#5  0x00007f40c2fc24a4 start_thread (libpthread.so.0)
#6  0x00007f40c3b0213d __clone (libc.so.6)

Stack trace of thread 886:
#0  0x00007f40c3af918d poll (libc.so.6)
#1  0x00007f40c69c0fbc n/a (libglib-2.0.so.0)
#2  0x00007f40c69c1342 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f40c377a236 n/a (libgio-2.0.so.0)
#4  0x00007f40c69e7715 n/a (libglib-2.0.so.0)
#5  0x00007f40c2fc24a4 start_thread (libpthread.so.0)
#6  0x00007f40c3b0213d __clone (libc.so.6)
```

```
segfault at ffffffff ip 00007f06549e82f4 sp 00007ffd67c5a4d8 error 4 in libQt5Gui.so.5.5.1[7f0654909000+528000]
systemd-coredump[5570]: Process 5303 (lxqt-panel) of user 1000 dumped core.

Stack trace of thread 5303:
#0  0x00007f06549e82f4 _ZNK15QPlatformScreen6screenEv (libQt5Gui.so.5)
#1  0x00007f064b41c39c _ZN10QXcbWindow6createEv (libQt5XcbQpa.so.5)
#2  0x00007f064b408e51 _ZNK15QXcbIntegration20createPlatformWindowEP7QWindow (libQt5XcbQpa.so.5)
#3  0x00007f0654a02714 _ZN14QWindowPrivate6createEb (libQt5Gui.so.5)
#4  0x00007f0654fe4d38 _ZN14QWidgetPrivate10create_sysEybb (libQt5Widgets.so.5)
#5  0x00007f0654fe5219 _ZN7QWidget6createEybb (libQt5Widgets.so.5)
#6  0x00007f0654fe5875 _ZN14QWidgetPrivate11createWinIdEy (libQt5Widgets.so.5)
#7  0x00007f0654fe36e7 _ZN7QWidget12setAttributeEN2Qt15WidgetAttributeEb (libQt5Widgets.so.5)
#8  0x00007f0654fe5758 _ZN14QWidgetPrivate11createWinIdEy (libQt5Widgets.so.5)
#9  0x00007f0654fe36e7 _ZN7QWidget12setAttributeEN2Qt15WidgetAttributeEb (libQt5Widgets.so.5)
#10 0x00007f0654fe349e _ZN7QWidget12setAttributeEN2Qt15WidgetAttributeEb (libQt5Widgets.so.5)
#11 0x00007f0654fe5758 _ZN14QWidgetPrivate11createWinIdEy (libQt5Widgets.so.5)
#12 0x00007f0654fe36e7 _ZN7QWidget12setAttributeEN2Qt15WidgetAttributeEb (libQt5Widgets.so.5)
#13 0x00007f0654fe5758 _ZN14QWidgetPrivate11createWinIdEy (libQt5Widgets.so.5)
#14 0x00007f0654fe48bb _ZNK7QWidget5winIdEv (libQt5Widgets.so.5)
#15 0x000000000048cfd0 n/a (lxqt-panel)
#16 0x000000000048d5f1 n/a (lxqt-panel)
#17 0x000000000048ca1f n/a (lxqt-panel)
#18 0x00007f06546b770f _ZN24QAbstractEventDispatcher17filterNativeEventERK10QByteArrayPvPl (libQt5Core.so.5)
#19 0x00007f064b404dc4 _ZN14QXcbConnection14handleXcbEventEP19xcb_generic_event_t (libQt5XcbQpa.so.5)
#20 0x00007f064b405b73 _ZN14QXcbConnection16processXcbEventsEv (libQt5XcbQpa.so.5)
#21 0x00007f06546ea1e1 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
#22 0x00007f0654fad9ac _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#23 0x00007f0654fb2e86 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#24 0x00007f06546babab _ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent (libQt5Core.so.5)
#25 0x00007f06546bcfa6 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
#26 0x00007f0654711143 n/a (libQt5Core.so.5)
#27 0x00007f06569b7dc7 g_main_context_dispatch (libglib-2.0.so.0)
#28 0x00007f06569b8020 n/a (libglib-2.0.so.0)
#29 0x00007f06569b80cc g_main_context_iteration (libglib-2.0.so.0)
#30 0x00007f065471154f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#31 0x00007f06546b857a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#32 0x00007f06546c053c _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#33 0x00000000004273d4 n/a (lxqt-panel)
#34 0x00007f0653a30610 __libc_start_main (libc.so.6)
#35 0x0000000000427a69 _start (lxqt-panel)

Stack trace of thread 5306:
#0  0x00007f0653aec16d __read (libc.so.6)
#1  0x00007f0656c8102e n/a (libmenu-cache.so.3)
#2  0x00007f06569de715 n/a (libglib-2.0.so.0)
#3  0x00007f0652fb94a4 start_thread (libpthread.so.0)
#4  0x00007f0653af913d __clone (libc.so.6)

Stack trace of thread 5309:
#0  0x00007f0653af018d poll (libc.so.6)
#1  0x00007f06409b2251 n/a (libpulse.so.0)
#2  0x00007f06409a3801 pa_mainloop_poll (libpulse.so.0)
#3  0x00007f06409a3e9e pa_mainloop_iterate (libpulse.so.0)
#4  0x00007f06409a3f50 pa_mainloop_run (libpulse.so.0)
#5  0x00007f06409b2199 n/a (libpulse.so.0)
#6  0x00007f064044ac98 n/a (libpulsecommon-8.0.so)
#7  0x00007f0652fb94a4 start_thread (libpthread.so.0)
#8  0x00007f0653af913d __clone (libc.so.6)

Stack trace of thread 5307:
#0  0x00007f0653af018d poll (libc.so.6)
#1  0x00007f06569b7fbc n/a (libglib-2.0.so.0)
#2  0x00007f06569b80cc g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f06569b8109 n/a (libglib-2.0.so.0)
#4  0x00007f06569de715 n/a (libglib-2.0.so.0)
#5  0x00007f0652fb94a4 start_thread (libpthread.so.0)
#6  0x00007f0653af913d __clone (libc.so.6)

Stack trace of thread 5308:
#0  0x00007f0653af018d poll (libc.so.6)
#1  0x00007f06569b7fbc n/a (libglib-2.0.so.0)
#2  0x00007f06569b8342 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f0653771236 n/a (libgio-2.0.so.0)
#4  0x00007f06569de715 n/a (libglib-2.0.so.0)
#5  0x00007f0652fb94a4 start_thread (libpthread.so.0)
#6  0x00007f0653af913d __clone (libc.so.6)

Stack trace of thread 5304:
#0  0x00007f0653af018d poll (libc.so.6)
#1  0x00007f0652b83ae2 n/a (libxcb.so.1)
#2  0x00007f0652b85757 xcb_wait_for_event (libxcb.so.1)
#3  0x00007f064b401379 n/a (libQt5XcbQpa.so.5)
#4  0x00007f06544d9b8e n/a (libQt5Core.so.5)
#5  0x00007f0652fb94a4 start_thread (libpthread.so.0)
#6  0x00007f0653af913d __clone (libc.so.6)
```

**Comment by pmattern** [comment]
Since release 0.10 quite a lot of changes have taken place in lxqt-panel so I wonder wether it still makes sense to try and track this down. Maybe it would be better to try and reproduce with more recent versions as described in https://github.com/lxde/lxqt/issues/945#issuecomment-183904590.
But maybe @palinek will know better.

**Comment by zjes** [comment]
It seems like https://bugreports.qt.io/browse/QTBUG-42985, I met this bug few month ago(#867) :(. Fixed in qt 5.6.

**Comment by palinek** [comment]
> It seems like https://bugreports.qt.io/browse/QTBUG-42985, I met this bug few month ago(#867) :(. Fixed in qt 5.6.

Indeed. @zjes thanks for letting us know... This could also be the reason for #671

**Comment by MttCastelli** [comment]
Since some days I always find a 'core' file on my home (wich is also my desktop): different weight, from 10 to 90 to 200 and more MB. I keep these files in trash, if yuo want. Wish it could help

**Comment by renegat** [comment]
Issue still persists with lxqt-panel-git 0.10.0.55.gb0f6d23-1

**Comment by rogerfranz** [comment]
Still persists. I don't have  a stacktrace, but I experience this frequently. The session simply disappears, sddm init restarts, and whatever I was working on is gone.

Fortunately, I save my work quite often.

uname -r: 4.4.0-42-generic
Lubuntu 16.04
i7, 16 GB of memory, plenty of disk space

lxqt versions:
lxqt-panel 0.10.0-8~ubuntu16.04.1
lxqt-runner 0.10.0-3

Here's a piece of a log, right after the latest instance:

Oct 12 22:24:34 firefly kernel: [ 2502.850503] show_signal_msg: 30 callbacks suppressed
Oct 12 22:24:34 firefly kernel: [ 2502.850508] lxqt-runner[1872]: segfault at 0 ip 00007f5dad438490 sp 00007ffe90f1f898 error 4 in libQt5DBus.so.5.5.1[7f5dad424000+7a000]
Oct 12 22:24:34 firefly kernel: [ 2502.854135] lxqt-panel[1870]: segfault at 0 ip 00007f6dbe1ec490 sp 00007ffca47cbac8 error 4 in libQt5DBus.so.5.5.1[7f6dbe1d8000+7a000]

**Comment by palinek** [comment]
Could it be this one? https://bugreports.qt.io/browse/QTBUG-47033 (fixed in Qt5.6, but ubuntu 16.04 ships with Qt5.5.1)

**Comment by rogerfranz** [comment]
It could be. Doesn't look exactly like what I'm seeing, but it could be.

**Comment by agaida** [comment]
ok - ancient
